#pragma once

#include "Camera01.h"
#include "Character.h"
#include "BackCastle.h"
#include "BackFrog.h"
#include "Gear.h"
#include "SceneChange.h"
#include "UI_GameStart.h"
#include "UI_Exit.h"
#include "UI_HowTo.h"
#include "BackMount.h"
#include "UI_credit.h"
#include "BackHorse.h"

#include "Clock.h"
#include "InGameManager.h"
#include "Second.h"
#include "Minute.h"
#include "BackGround.h"
#include "Character1.h"
#include "Character2.h"
#include "Character3.h"
#include "Character4.h"